#!/usr/bin/bash

~/.config/bspwm/autostart.sh &

bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor DP-0 -d 1 2 3 4 5 6 7
bspc monitor HDMI-0 -d 7 8 9

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

names=("" "" "" "" "" "" "" "" "" "")
for i in {1..10}
do
	bspc desktop \^$i -n ${names[$i]}
done
